### ISSUE TITLE
Consider migration to preservim

### ISSUE THREAD

**Issue by alerque** [preservim/vim-indent-guides#149]
Besides the long term lack of activity, I noticed you have marked this as being unmaintained. First of all thanks for the contribution to the VIM plugin space, I have used this for years myself still appreciate it.

I would like to ask if you would be interested in migrating this to the @preservim org namespace. I and a couple other folks have managed this for a few years now as a neutral place to house aging but still useful plugins that still get some community traction but the maintainers have moved on and want to let them go a little bit. We started with `nerdcommentor` and also now manage `nerdtere`, `tagbar`, `vim-markdown`, and quite a few others.

The idea is that I and a few others (to include yourself) would just keep an eye out on community contributions and find contributors who have a good track record and give them a little bit more permissions to help with maintenance. My usual modus is to setup a team form anyone ⓐ interested and ⓑ with a previous positive track record of contributions such that the team can manage issues and merge PRs pending at least one other approval and passing CI checks.

If agreeable I would keep you on as owner of the repo but also myself be able to invite people to the team for this plugin. GitHub handles redirects from the old repository location, so most users of the plugin would hardly notice the change. My first order of business would be to setup some basic CI checks to make sure PRs don't outright break basic functionality and then look through the issue tracker and past PRs looking for existing contributions that should be included and with a weather eye out on if there is anybody to invite to help with maintenance.

I can't promise anybody will step up run with it, but at least the friction will be lowered on contributions so that there is a chance any needed fixes or improvements can get through.

If your are interested in this let me know and I'll invite you to the org and we can get started.

**Comment by neingeist** [comment]
This sounds like a great idea!

**Comment by alerque** [comment]
We kind of need some buy-in from @nathanaelkane to proceed. As an org our goal is not to just fork plugins but to become the canonical source for existing users. Doing this without friction and requiring existing users to find the fork and switch requires the original owner's blessing.

It isn't hard to setup and won't take any time going forward (if he doesn't want to participate although he would continue to have owner access if he did feel so inclined) but we would need him to get started by transferring the repo.

**Comment by nathanaelkane** [comment]
Hi @alerque, sounds like a great idea, I'd be happy to migrate this across. 👍

**Comment by nathanaelkane** [comment]
Ownership has been transferred to PreserVIM, thanks @alerque.

**Comment by alerque** [comment]
@nathanaelkane You should have an invite to the org. When you accept that you should have enough mojo to use GitHub's `Transfer repository` option in settings and move this repository to the org namespace. That will also setup Git + HTTP redirects so nobody with this is their plugin managers get disconnected. My only major suggestion after that is for you to *not fork a copy of the repo back to your personal GitHub namespace* because that will clear the redirects. I'll still be the owner of the repo in the PreserVIM namespace and can work on it there if you like.

After it's migrated over I can setup a team for it if other people want to join as maintainers and setup some CI to keep everybody out of trouble.

**Comment by alerque** [comment]
Jinx ... I got distracted and that sat as a draft too long.

The not about *not* making a new fork in your personal namespace is still relevant so we don't kill off the nice redirect stuff.

**Comment by nathanaelkane** [comment]
Yep all sounds good, thanks.

**Comment by alerque** [comment]
If anybody wants to contribute going forward the best place to start is sending a PR or commenting on existing issues with anything that helps moving them toward resolution. I'll be keeping an eye out and offering elevated privileges on this repo (based on interest and contributions) to help facilitate issue triage and code contributions.
